newline_style = "Unix"
indent_style = "Block"

group_imports = "StdExternalCrate"
imports_granularity = "Crate"

enum_discrim_align_threshold = 40
struct_field_align_threshold = 40

match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true

binop_separator = "Front"
overflow_delimited_expr =  true

reorder_impl_items = true
use_field_init_shorthand = true

format_code_in_doc_comments = true
format_strings = true

wrap_comments = true

error_on_line_overflow = true
error_on_unformatted = true
